/***********************************************************/
/*       This file is part of the UndeadRemains Mod        */
/*      which is maintained by DivergingLense Studios      */
/*          and is published under the MIT License         */
/* https://github.com/DivergingLenseStudios/Undead-Remains */
/***********************************************************/

package net.diverginglensestudios.undeadremains.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class StrayZombieAnimations {


public static final AnimationDefinition STRAY_ZOMBIE_WALK = AnimationDefinition.Builder.withLength(2f).looping()
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.29167f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, 1f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.70833f, KeyframeAnimations.posVec(0f, -0.7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.70833f, KeyframeAnimations.posVec(0f, -0.7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-95f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.2f, KeyframeAnimations.degreeVec(-100.14f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.4f, KeyframeAnimations.degreeVec(-102.61f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(-103f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6000000000000001f, KeyframeAnimations.degreeVec(-102.86f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.8f, KeyframeAnimations.degreeVec(-100.77f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(-95f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.2f, KeyframeAnimations.degreeVec(-101.9f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.4f, KeyframeAnimations.degreeVec(-104.81f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.45833f, KeyframeAnimations.degreeVec(-105f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(-104.4f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.7999999999999998f, KeyframeAnimations.degreeVec(-101.01f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(-95f, 12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-95f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.2f, KeyframeAnimations.degreeVec(-102.16f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.4f, KeyframeAnimations.degreeVec(-104.81f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-105f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.6000000000000001f, KeyframeAnimations.degreeVec(-104.51f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.8f, KeyframeAnimations.degreeVec(-101.51f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(-95f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.2f, KeyframeAnimations.degreeVec(-101.18f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.4f, KeyframeAnimations.degreeVec(-104.52f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(-105f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5999999999999999f, KeyframeAnimations.degreeVec(-104.73f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.7999999999999998f, KeyframeAnimations.degreeVec(-101.66f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(-95f, -12.5f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.29167f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.41667f, KeyframeAnimations.posVec(0f, 1f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.29167f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
public static final AnimationDefinition STRAY_ZOMBIE_ATTACK = AnimationDefinition.Builder.withLength(1f)
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.79167f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-13.13f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.54167f, KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-100f, 0f, 12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.54167f, KeyframeAnimations.degreeVec(32.5f, 0f, 12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.58333f, KeyframeAnimations.degreeVec(32.5f, 0f, 12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-15f, 0f, 8.35f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-100f, 0f, -12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.54167f, KeyframeAnimations.degreeVec(32.5f, 0f, -12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.58333f, KeyframeAnimations.degreeVec(32.5f, 0f, -12.5f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.75f, KeyframeAnimations.degreeVec(-15f, 0f, -8.35f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
}
