package net.diverginglensestudios.undeadremains.entity.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class XanarianCannibalAnimations {
public static final AnimationDefinition XANARIAN_CANNIBAL_WALK = AnimationDefinition.Builder.withLength(2f).looping()
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.66667f, KeyframeAnimations.degreeVec(3f, 4.48f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.66667f, KeyframeAnimations.degreeVec(3f, -4.48f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.70833f, KeyframeAnimations.posVec(0f, -0.7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.45833f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.70833f, KeyframeAnimations.posVec(0f, -0.7f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("head",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(4.76f, -4.48f, -3.34f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.66667f, KeyframeAnimations.degreeVec(3f, -4.48f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.08333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.375f, KeyframeAnimations.degreeVec(4.76f, 4.48f, 3.34f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.66667f, KeyframeAnimations.degreeVec(3f, 4.48f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.16667f, KeyframeAnimations.posVec(0f, 1f, -1.67f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.33333f, KeyframeAnimations.posVec(0f, 1.62f, -2.54f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.41667f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.625f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, 1f, -1.67f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.33333f, KeyframeAnimations.posVec(0f, 1.62f, -2.54f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.29167f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.41667f, KeyframeAnimations.posVec(0f, 1f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.20833f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.375f, KeyframeAnimations.posVec(0f, -1f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.5f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.20833f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -1f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.29167f, KeyframeAnimations.posVec(0f, 2f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.41667f, KeyframeAnimations.posVec(0f, 1f, -1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.5f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.29167f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("spine",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.45833f, KeyframeAnimations.posVec(0f, -0.3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.45833f, KeyframeAnimations.posVec(0f, -0.3f, 0f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
public static final AnimationDefinition XANARIAN_CANNIBAL_RUN = AnimationDefinition.Builder.withLength(1.25f).looping()
.addAnimation("spine",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.45833f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.08333f, KeyframeAnimations.posVec(0f, -3f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("spine",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.20833f, KeyframeAnimations.posVec(0f, 3f, -1.91f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 4f, -0.76f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-52.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.58333f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.91667f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.20833f, KeyframeAnimations.posVec(0f, 3f, -1.91f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 3f, -0.76f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -4f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, 1f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.95833f, KeyframeAnimations.posVec(0f, 0f, 3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(47.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.95833f, KeyframeAnimations.degreeVec(42.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.625f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(0.95833f, KeyframeAnimations.posVec(0f, 0f, 3f),
			AnimationChannel.Interpolations.CATMULLROM), 
		new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 0f, -2f),
			AnimationChannel.Interpolations.CATMULLROM)))
.addAnimation("leg_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.625f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.95833f, KeyframeAnimations.degreeVec(42.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(1.25f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
public static final AnimationDefinition XANARIAN_CANNIBAL_ATTACK = AnimationDefinition.Builder.withLength(0.58333f)
.addAnimation("spine",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.20833f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.45833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("torso",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0.08333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.POSITION, 
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.20833f, KeyframeAnimations.posVec(0f, -1f, 0f),
			AnimationChannel.Interpolations.LINEAR), 
		new Keyframe(0.58333f, KeyframeAnimations.posVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_right",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.20833f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR),
		new Keyframe(0.58333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.LINEAR)))
.addAnimation("arm_left",
	new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.125f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.25f, KeyframeAnimations.degreeVec(-19.31f, 5.25f, -9.67f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.375f, KeyframeAnimations.degreeVec(-34.36f, 16.56f, -2.41f),
			AnimationChannel.Interpolations.CATMULLROM),
		new Keyframe(0.58333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
			AnimationChannel.Interpolations.CATMULLROM))).build();
}